name: Refresh GitHub Pages RPM repo
permissions:
  contents: write
  pages: write
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare RPM tree
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y createrepo-c curl jq gh
          mkdir -p rpm-repo/el9/{x86_64,aarch64}

      - name: Fetch Vesktop RPMs
        run: |
          # 1. Query the public API for the latest release tag
          ver=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/Vencord/Vesktop/releases/latest \
            | jq -r .tag_name)
          echo "Latest upstream Vesktop release: $ver"

          # 2. Strip leading "v" from tag if present
          ver_no_v=${ver#v}

          # 3. Download both architecture RPMs
          curl -L \
            "https://vencord.dev/download/vesktop/amd64/rpm/vesktop-${ver_no_v}.x86_64.rpm" \
            -o rpm-repo/el9/x86_64/vesktop-${ver_no_v}.x86_64.rpm

          curl -L \
            "https://vencord.dev/download/vesktop/arm64/rpm/vesktop-${ver_no_v}.aarch64.rpm" \
            -o rpm-repo/el9/aarch64/vesktop-${ver_no_v}.aarch64.rpm

      - name: Update repo metadata
        run: |
          createrepo_c --update rpm-repo/el9/x86_64
          createrepo_c --update rpm-repo/el9/aarch64
          touch rpm-repo/.nojekyll
          
      - name: Configure commit identity
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit & push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./rpm-repo
          publish_branch: gh-pages
