name: Refresh Copr SRPM
permissions:
  contents: read

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  copr:
    runs-on: ubuntu-latest
    container: fedora:latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # Use DNF inside the Fedora container
          dnf install -y \
            rpm \
            rpm-build \
            rpmdevtools \
            copr-cli \
            gh \
            jq \
            curl

      - name: Set up rpmbuild tree
        run: |
          mkdir -p ~/.cache-builds/rpmbuild/{SOURCES,SRPMS,SPECS,BUILD,RPMS}
          echo '%_topdir %(echo $HOME)/.cache-builds/rpmbuild' > ~/.rpmmacros

      - name: Refresh sources
        working-directory: copr
        env:
          # Allow gh to authenticate
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./refresh-sources.sh

      - name: Build SRPM
        working-directory: copr
        run: |
          ver=$(basename ~/.cache-builds/rpmbuild/SOURCES/vesktop-*.x86_64.rpm \
                .x86_64.rpm | cut -d- -f2)
          rpmbuild -bs vesktop.spec --define "version_override $ver"

      - name: Restore Copr config
        run: |
          mkdir -p ~/.config
          echo "${{ secrets.COPR_CONFIG_B64 }}" \
            | base64 --decode \
            | tar xz -C ~/.config
            - name: Push to Copr
              run: |
                srpm=$(ls ~/.cache-builds/rpmbuild/SRPMS/vesktop-*.src.rpm | tail -1)
                copr-cli build vesktop "$srpm"

      - name: Push to Copr
        run: |
          srpm=$(ls ~/.cache-builds/rpmbuild/SRPMS/vesktop-*.src.rpm | tail -1)
          copr-cli build vesktop "$srpm"
